In [14]:
import numpy as np
import pandas as pd
import random
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

In [2]:
df = pd.read_csv('../DATA/npr.csv')
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [3]:
df.shape

(11992, 1)

In [4]:
df.isnull().sum()

Article    0
dtype: int64

In [5]:
df['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [6]:
count_vect = CountVectorizer(stop_words='english',max_df=0.9,min_df=2)

In [8]:
dtm = count_vect.fit_transform(df.Article)

In [9]:
dtm.shape

(11992, 54777)

In [10]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [11]:
lda = LatentDirichletAllocation(n_components=10,random_state=101)
lda.fit(dtm)

LatentDirichletAllocation(random_state=101)

In [12]:
count_vect.get_feature_names()[468]

C:\Users\hp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'209'

In [13]:
count_vect.get_feature_names_out()[1179]

'999'

In [21]:
count_vect.get_feature_names_out()[random.randint(0,54777)]

'orbit'

In [29]:
lda.components_

array([[4.24691106e+01, 1.91331365e+02, 1.00000000e-01, ...,
        6.09992247e+00, 1.09999503e+00, 1.00000000e-01],
       [1.79038266e+00, 2.05450905e+02, 1.00000000e-01, ...,
        1.00000176e-01, 1.00000000e-01, 1.00000146e-01],
       [6.67336160e+00, 8.89024579e+01, 1.00000000e-01, ...,
        1.00003140e-01, 1.00000000e-01, 1.00000025e-01],
       ...,
       [1.00016827e-01, 2.03909407e+02, 1.00000000e-01, ...,
        1.00009040e-01, 1.00003439e-01, 1.00001731e-01],
       [4.01563835e+00, 4.74913378e+01, 3.10000000e+00, ...,
        1.00031213e-01, 1.00000146e-01, 2.09999739e+00],
       [5.77794196e+00, 2.39961868e+03, 1.00000000e-01, ...,
        1.00006754e-01, 1.00001261e-01, 1.00000000e-01]])

In [46]:
lda.components_.shape

(10, 54777)

In [48]:
len(lda.components_)

10

In [40]:
first_topic = lda.components_[0]
first_topic

array([4.24691106e+01, 1.91331365e+02, 1.00000000e-01, ...,
       6.09992247e+00, 1.09999503e+00, 1.00000000e-01])

In [42]:
top_10_words = first_topic.argsort()[-10:]
top_10_words

array([54412, 53211, 49183, 39848, 49459, 27439, 36283, 26752, 42993,
       28659], dtype=int64)

In [43]:
for idx in top_10_words:
    print(count_vect.get_feature_names_out()[idx])

years
way
think
really
time
know
people
just
says
like


In [45]:
for idx, topic in enumerate(lda.components_):
    print(f"The top 20 words for topic {idx}: ")
    print([count_vect.get_feature_names_out()[idx] for idx in topic.argsort()[-20:]])
    print('-----------------------------------')
    print('-----------------------------------')

The top 20 words for topic 0: 
['make', 'didn', 'got', 've', 'things', 'story', 'going', 'life', 'don', 'new', 'years', 'way', 'think', 'really', 'time', 'know', 'people', 'just', 'says', 'like']
-----------------------------------
-----------------------------------
The top 20 words for topic 1: 
['democrats', 'people', 'obama', 'presidential', 'hillary', 'new', 'donald', 'democratic', 'sanders', 'vote', 'election', 'party', 'voters', 'president', 'republican', 'state', 'campaign', 'said', 'clinton', 'trump']
-----------------------------------
-----------------------------------
The top 20 words for topic 2: 
['department', 'congress', 'fbi', 'government', 'office', 'told', 'comey', 'intelligence', 'news', 'russian', 'committee', 'new', 'russia', 'administration', 'obama', 'white', 'house', 'said', 'president', 'trump']
-----------------------------------
-----------------------------------
The top 20 words for topic 3: 
['make', 'year', 'world', 'percent', 'research', 'don', 'resear

In [49]:
topics_assigned = lda.transform(dtm)
topics_assigned.shape

(11992, 10)

In [52]:
len(topics_assigned.argmax(axis=1))

11992

In [53]:
df['Topic'] = topics_assigned.argmax(axis=1)

In [54]:
df.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      2
1    Donald Trump has used Twitter  —   his prefe...      2
2    Donald Trump is unabashedly praising Russian...      2
3  Updated at 2:50 p. m. ET, Russian President Vl...      2
4  From photography, illustration and video, to d...      9

In [55]:
df.Topic.unique()

array([2, 9, 6, 0, 3, 8, 7, 5, 1, 4], dtype=int64)